# In this notebook we are looking for miner the rules in our data

In [1]:
import pandas as pd
ready = pd.read_csv('source/ready_data.csv')

/home/visus/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
ready

,sexo,local_origem,tipo_instituicao,renda_familiar,tipo_residencia,grau_escolaridade,motivo,transporte,instrucao_pai,instrucao_mae,automovel,livros,leitura,internet,age_interval,score_interval,class_period,course_name,degree
0,M,Zona Urbana,Apenas em escola pública,"Maior que R$ 1530,00",Alugada,Médio Completo,Realização pessoal,próprio,Ensino Médio Incompleto,Ensino Médio Completo,Sim,Nenhum livro,Outro,Diariamente,Age between 22 and 30,Score 27 - 36,integral,ENGENHARIA AGRONÔMICA,Bacharel
1,M,Zona Rural,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Fundamental,Realização pessoal,ônibus/van,Ensino Fundam. incompleto,Ensino Fundam. incompleto,Sim,1 ou 2 livros,Outro,Não utiliza,Age less than 17,Score 45 - 54,integral,AGROPECUÁRIA,Ensino Médio e Técnico
2,F,Zona Urbana,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Médio Completo,Possibilidades no mercado de trabalho,carona,Ensino Fundam. incompleto,Ensino Fundamental Completo,Não,1 ou 2 livros,Outro,Diariamente,Age between 22 and 30,Score 54 - 63,noturno,INFORMÁTICA,Técnico
3,M,Zona Urbana,Apenas em escola pública,"R$ 1276,00 a 1530,00",Própria,Médio Completo,outro motivo,ônibus/van,Ensino Médio Completo,Ensino Médio Incompleto,Sim,1 ou 2 livros,Ficção,Diariamente,Age between 17 and 22,Score 54 - 63,integral,AGROPECUÁRIA,Técnico
4,F,Zona Urbana,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Médio Incompleto,Possibilidades no mercado de trabalho,ônibus/van,Ensino Fundam. incompleto,Ensino Médio Completo,Sim,Mais de 5 livros,Outro,Diariamente,Age between 17 and 22,Score 45 - 54,noturno,CIÊNCIA DA COMPUTAÇÃO,Bacharel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,M,Zona Urbana,Apenas em escola pública,"R$ 766,00 a 1275,00",Própria,Médio Incompleto,Contribuição para a sociedade,ônibus/van,Ensino Fundam. incompleto,Ensino Médio Incompleto,Sim,1 ou 2 livros,Ficção,Diariamente,Age between 22 and 30,Score 27 - 36,noturno,EDUCAÇÃO FÍSICA,Bacharel
1322,F,Zona Urbana,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Médio Completo,Possibilidades no mercado de trabalho,ônibus/van,Ensino Médio Completo,Ensino Fundam. incompleto,Sim,1 ou 2 livros,Outro,Diariamente,Age between 22 and 30,Score 27 - 36,noturno,ENFERMAGEM,Técnico
1323,M,Zona Rural,Apenas em escola pública,"R$ 766,00 a 1275,00",Própria,Fundamental,Possibilidades no mercado de trabalho,ônibus/van,Ensino Fundam. incompleto,Ensino Fundam. incompleto,Sim,1 ou 2 livros,Romance,Diariamente,Age less than 17,Score 54 - 63,integral,AGROPECUÁRIA,Ensino Médio e Técnico
1324,F,Zona Urbana,Apenas em escola pública,"R$ 1276,00 a 1530,00",Própria,Médio Completo,Realização pessoal,ônibus/van,Ensino Fundamental Completo,Ensino Fundamental Completo,Não,1 ou 2 livros,Romance,Diariamente,Age between 17 and 22,Score 18 - 27,noturno,EDUCAÇÃO FÍSICA,Licenciatura
1325,M,Zona Urbana,Apenas em escola pública,"R$ 766,00 a 1275,00",Própria,Médio Completo,Realização pessoal,carona,Ensino Fundam. incompleto,Ensino Fundam. incompleto,Sim,1 ou 2 livros,Outro,Semanalmente (algumas vezes),Age between 17 and 22,Score 18 - 27,integral,ENGENHARIA AGRONÔMICA,Bacharel